language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed 06122019/udagram-api-feed:f1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user 06122019/udagram-api-user:f1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend 06122019/udagram-frontend:f1
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy 06122019/reverseproxy:f1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 06122019/udagram-frontend:f1
  - docker push 06122019/udagram-api-feed:f1
  - docker push 06122019/udagram-api-user:f1
  - docker push 06122019/reverseproxy:f1

